### ISSUE TITLE
Investigate and try to fix warnings in storybook

### ISSUE THREAD

**Issue by orange-buffalo** [orange-buffalo/simple-accounting#252]
```
  console.warn
    [vue-router] Named Route 'root' has a default child route. When navigating to this named route (:to="{name: 'root'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.

      at warn (node_modules/vue-router/dist/vue-router.common.js:18:47)
      at addRouteRecord (node_modules/vue-router/dist/vue-router.common.js:1376:9)
      at node_modules/vue-router/dist/vue-router.common.js:1288:5
          at Array.forEach (<anonymous>)
      at createRouteMap (node_modules/vue-router/dist/vue-router.common.js:1287:10)
      at createMatcher (node_modules/vue-router/dist/vue-router.common.js:1477:13)
      at new VueRouter (node_modules/vue-router/dist/vue-router.common.js:2794:18)

console.warn
    Unexpected error: TypeError: Cannot set property 'parameters' of undefined

      at Object.warn (node_modules/@storybook/client-logger/dist/index.js:53:73)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:149:34
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:142:20
          at Array.forEach (<anonymous>)
      at node_modules/@storybook/core/dist/client/preview/loadCsf.js:141:12
      at ConfigApi.configure (node_modules/@storybook/client-api/dist/config_api.js:26:7)
```

**Comment by orange-buffalo** [comment]
Will not do, we will remove storybook soon.
